### ISSUE TITLE
Moving incorrect files in BUILD.sh

### ISSUE THREAD

**Issue by ZetaDaemon** [SomeRanDev/Godot-Trail3D#1]
BUILD.sh tries to move `target/debug/godot_trail_3d.dll` and `target/release/godot_trail_3d.dll` instead of `target/debug/godot_trail_3d.so` and `target/release/godot_trail_3d.so`

**Comment by SomeRanDev** [comment]
Whoops, I'm not on Linux, so the BUILD.sh was thrown together haphazardly. 😅 Fixed w e2b9a10!
