### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by sweden-moose** [SomeRanDev/Godot-Trail3D#4]
Hi, your readme says 

> This version is rewritten from GDScript to Rust, and it's optimized to remove the expensive list manipulations.

Does this optimization affects performance in a good way?

![image](https://github.com/SomeRanDev/Godot-Trail3D/assets/63788778/eeef8d07-11f9-4fc1-87b5-669950b8ff1a)
Above you can see gdscript implementation from [this gist](https://gist.github.com/geegaz/8dfd61f600828c02acbbdaa749a2bbd5) for 300 moving nodes in one scene 

![image](https://github.com/SomeRanDev/Godot-Trail3D/assets/63788778/63667ee5-a979-4d44-9a7b-4c5ca9504a48)
And this is rust implementation for same 300 moving nodes. 

Test project (with my linux addon build): [TestProject.zip](https://github.com/user-attachments/files/15859881/TestProject.zip)

**Comment by SomeRanDev** [comment]
I downloaded the project and tried, but I wasn't able to replicate the results. The GDScript version seemed slower, but I wasn't sure? There seemed to be no difference. I was using 4.3beta. 

There appears to be lag and peaks right at the start when all the objects are spawned, maybe using GDExtension makes the object spawning slower? Could you try object pooling and checking the Process Time after they have been spawned for a bit?

**Comment by sweden-moose** [comment]
I tried running project again and your implementation was like 20-30% faster, even on spawn. So, i think its resolved.
